-- MySQL Script generated by MySQL Workbench
-- Wed Aug 31 19:16:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema jtsec2
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surame` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projects_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projects_has_users` (
  `projects_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `role_type` ENUM('user', 'responsable', 'participante') NOT NULL,
  PRIMARY KEY (`projects_id`, `users_id`),
  INDEX `fk_projects_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_projects_has_users_projects1_idx` (`projects_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_has_users_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  `projects_has_users_projects_id` INT NOT NULL,
  `projects_has_users_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activities_projects_has_users1_idx` (`projects_has_users_projects_id` ASC, `projects_has_users_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_activities_projects_has_users1`
    FOREIGN KEY (`projects_has_users_projects_id` , `projects_has_users_users_id`)
    REFERENCES `mydb`.`projects_has_users` (`projects_id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incidences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  `ACTIVITIES_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ACTIVITIES_id`),
  INDEX `fk_INCIDENCES_ACTIVITIES1_idx` (`ACTIVITIES_id` ASC) VISIBLE,
  CONSTRAINT `fk_INCIDENCES_ACTIVITIES1`
    FOREIGN KEY (`ACTIVITIES_id`)
    REFERENCES `mydb`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
